import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
const BASE='http://127.0.0.1:4206',OUT=path.join(process.cwd(),'qa-artifacts','ambassador-rail');fs.mkdirSync(OUT,{recursive:true});
const must=(c,m)=>{if(!c)throw new Error(m)};const server=spawn('python3',['-m','http.server','4206','--bind','127.0.0.1'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,900));const browser=await chromium.launch({headless:true});
const keys=['ambassadors','promoters','community'];
async function seed(page){return page.evaluate(()=>{const Store=window.NSV421Store,s=Store.load();const ids=(s.media||[]).filter(m=>m.cat==='People'&&Store.eligibleForPublic(s,m)).map(m=>m.id).slice(0,8);if(ids.length<4)throw new Error('not enough approved People media to verify three streams');s.peopleStreams=s.peopleStreams||{};const orders={ambassadors:ids.slice(0,3),promoters:[...ids.slice(0,4)].reverse(),community:ids.slice(1,5)};for(const key of ['ambassadors','promoters','community'])s.peopleStreams[key]={...(s.peopleStreams[key]||{}),enabled:true,selectedIds:orders[key],title:`QA ${key}`,subtitle:`QA ${key} public copy`,direction:key==='promoters'?'rtl':'ltr',speed:12,desktopLimit:0,tabletLimit:0,mobileLimit:0,deviceVisibility:{}};if(orders.community[0])s.peopleStreams.community.deviceVisibility[orders.community[0]]={desktop:true,tablet:true,mobile:false};Store.save(s);window.dispatchEvent(new CustomEvent('nsv421:change'));return orders;});}
async function snapshot(page){return page.evaluate(()=>{const out={};for(const key of ['ambassadors','promoters','community']){const sec=document.querySelector(`#people-${key}`),track=sec?.querySelector('.v25-story-track'),groups=[...sec?.querySelectorAll('.v25-story-group')||[]],primary=sec?.querySelector('.v25-story-group[data-v25-primary="1"]'),cs=track?getComputedStyle(track):null;out[key]={exists:!!sec,mode:sec?.dataset.streamMode,groups:groups.length,copies:+track?.dataset.loopCopies||groups.length,loopDistance:+track?.dataset.loopDistance||0,ids:[...primary?.querySelectorAll('.v25-story-person')||[]].map(x=>x.dataset.id),broken:[...sec?.querySelectorAll('img')||[]].filter(i=>i.complete&&i.naturalWidth===0).map(i=>i.src),title:sec?.querySelector('h3')?.textContent?.trim()||'',direction:track?.classList.contains('reverse')?'rtl':'ltr',transform:cs?.transform||'none',animation:cs?.animationName||'none',playState:cs?.animationPlayState||'none'};}return {streams:out,overflow:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)-innerWidth,leakedAdminCopy:/Admin controls image selection|FULL-PICTURE TREATMENT/i.test(document.body.innerText)};});}
async function coverage(page,key){return page.evaluate(k=>{const sec=document.querySelector(`#people-${k}`),vp=sec?.querySelector('.v25-story-viewport');if(!vp)return {ok:false};const vr=vp.getBoundingClientRect(),groups=[...sec.querySelectorAll('.v25-story-group')].map(g=>g.getBoundingClientRect()).sort((a,b)=>a.left-b.left);let cursor=vr.left,maxGap=0;for(const r of groups){if(r.right<vr.left||r.left>vr.right)continue;maxGap=Math.max(maxGap,Math.max(0,r.left-cursor));cursor=Math.max(cursor,r.right);}const rightEdgeGap=Math.max(0,vr.right-cursor);return {ok:rightEdgeGap<=20&&maxGap<=20,left:groups[0]?.left,right:groups.at(-1)?.right,viewportLeft:vr.left,viewportRight:vr.right,maxGap,rightEdgeGap};},key);}
async function check(width,height,label){const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:width<600?3:2,hasTouch:true,serviceWorkers:'block',reducedMotion:'no-preference'});const page=await context.newPage(),errs=[];page.on('pageerror',e=>errs.push(String(e)));await page.goto(BASE+'/people-of-nariyal-sutra.html',{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(700);const orders=await seed(page);await page.waitForFunction(()=>['ambassadors','promoters','community'].every(k=>document.querySelector(`#people-${k} .v25-story-group[data-v25-primary="1"] .v25-story-person`)),null,{timeout:8000});await page.waitForTimeout(300);const before=await snapshot(page);for(let phase=0;phase<4;phase++){for(const key of keys){const c=await coverage(page,key);must(c.ok,`${label}: ${key} blank rail tail/gap at phase ${phase}: ${JSON.stringify(c)}`);}await page.waitForTimeout(550);}const after=await snapshot(page);
 for(const key of keys){const got=after.streams[key],prior=before.streams[key];must(got.exists,`${label}: ${key} stream missing`);const expected=orders[key].filter((id,i)=>!(key==='community'&&label==='mobile'&&i===0));must(JSON.stringify(got.ids)===JSON.stringify(expected),`${label}: ${key} Admin sequence did not propagate expected=${JSON.stringify(expected)} got=${JSON.stringify(got.ids)}`);must(new Set(got.ids).size===got.ids.length,`${label}: duplicate IDs in primary ${key} group`);must(!got.broken.length,`${label}: broken ${key} images ${got.broken.join(',')}`);must(got.title===`QA ${key}`,`${label}: ${key} title did not propagate`);if(key==='promoters')must(got.direction==='rtl',`${label}: promoter direction did not propagate`);if(expected.length>=2){must(got.mode==='loop'&&got.groups>=2&&got.copies>=2&&got.loopDistance>0,`${label}: ${key} rail is not continuous ${JSON.stringify(got)}`);must(got.animation&&got.animation!=='none'&&got.playState==='running',`${label}: ${key} marquee animation not running ${JSON.stringify(got)}`);must(prior.transform!==got.transform,`${label}: ${key} rail did not measurably move`);}}
 must(!after.leakedAdminCopy,`${label}: internal Admin helper copy leaked onto public People page`);must(after.overflow<=8,`${label}: page horizontal overflow ${after.overflow}`);await page.evaluate(()=>{const Store=window.NSV421Store,s=Store.load();s.peopleStreams.community.enabled=false;Store.save(s);window.dispatchEvent(new CustomEvent('nsv421:change'));});await page.waitForTimeout(120);must(!(await page.locator('#people-community').count()),`${label}: hidden Community stream still rendered`);await page.screenshot({path:path.join(OUT,`${label}.png`),fullPage:true});must(!errs.length,`${label}: page errors ${errs.join(' | ')}`);await context.close();}
try{await check(1440,900,'desktop');await check(820,1100,'tablet');await check(390,844,'mobile');console.log('PEOPLE CONTINUOUS RAIL QA: PASS');}finally{await browser.close();server.kill();}
