import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
const BASE=process.env.NS_QA_BASE||'http://127.0.0.1:4173',OUT=path.resolve(process.env.NS_QA_OUT||'qa-artifacts');fs.mkdirSync(OUT,{recursive:true});
const failures=[],checks=[],fail=(s,m)=>failures.push({scope:s,msg:m});
const browser=await chromium.launch({headless:true});
try{
 async function audit(viewport,label){
  const page=await browser.newPage({viewport});await page.goto(`${BASE}/index.html?cinematic=${Date.now()}`,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(1800);
  const boot=await page.evaluate(()=>{const film=document.querySelector('#v20-story-film'),items=[...document.querySelectorAll('.v421-fall-coconut')],frame=document.querySelector('.v421-cut-frame.hero'),visible=e=>!!e&&getComputedStyle(e).display!=='none'&&getComputedStyle(e).visibility!=='hidden'&&Number(getComputedStyle(e).opacity||1)>.01;return{runtime:window.NSV421CinematicFinal?.version||'',items:items.length,filmRatio:(film?.offsetHeight||0)/innerHeight,maxWidth:Math.max(0,...items.map(x=>x.getBoundingClientRect().width)),blend:items[0]?getComputedStyle(items[0]).mixBlendMode:'',cutFrame:!!frame,legacyHero:visible(document.querySelector('#v20-story-coconut')),legacyKnife:[...document.querySelectorAll('.v20-knife,.knife.v20-knife')].some(visible),legacyStream:[...document.querySelectorAll('.water-stream')].some(visible)}});
  checks.push({scope:`${label}:boot`,...boot});if(boot.runtime!=='natural-waves-protected-cut')fail(`${label}:boot`,`wrong runtime ${boot.runtime}`);if(boot.items!==100)fail(`${label}:boot`,`expected 100 total harvest fruits, found ${boot.items}`);if(boot.filmRatio<2.2||boot.filmRatio>2.5)fail(`${label}:boot`,`runway not compact (${boot.filmRatio.toFixed(2)}x)`);if(boot.maxWidth>72)fail(`${label}:boot`,`rain fruit too large (${boot.maxWidth.toFixed(0)}px)`);if(boot.blend!=='multiply')fail(`${label}:boot`,`rain fruit is not visually integrated (${boot.blend})`);if(!boot.cutFrame)fail(`${label}:boot`,'protected cut frame missing');if(boot.legacyHero||boot.legacyKnife||boot.legacyStream)fail(`${label}:boot`,'broken legacy overlay visible');
  async function at(p,name){await page.evaluate(p=>{document.documentElement.style.scrollBehavior='auto';const f=document.querySelector('#v20-story-film'),top=f.getBoundingClientRect().top+scrollY,range=Math.max(1,f.offsetHeight-innerHeight);scrollTo(0,top+range*p);window.NSV421CinematicFinal?.update?.();dispatchEvent(new Event('scroll'))},p);await page.waitForTimeout(360);const st=await page.evaluate(()=>{window.NSV421CinematicFinal?.update?.();const S=window.__NS_V421_CINEMATIC_STATE||{},op=e=>e?Number(getComputedStyle(e).opacity||0):0,rect=e=>e?.getBoundingClientRect();return{...S,hero:op(document.querySelector('.v421-cut-frame.hero')),body:op(document.querySelector('.v421-cut-frame.body')),cap:op(document.querySelector('.v421-cut-frame.cap')),knife:op(document.querySelector('.v421-local-knife')),water:op(document.querySelector('.v421-water-finish')),frameRect:rect(document.querySelector('.v421-cut-frame.hero'))}});checks.push({scope:`${label}:${name}`,...st});await page.screenshot({path:path.join(OUT,`cinematic-${label}-${name}.png`)});return st}
  for(const [p,name] of [[.12,'rain-wave-1'],[.22,'rain-wave-2'],[.32,'rain-wave-3']]){const s=await at(p,name);if(s.visibleRain<7)fail(`${label}:${name}`,`too few falling coconuts (${s.visibleRain})`);if(s.visibleRain>32)fail(`${label}:${name}`,`looks like a wall instead of rain (${s.visibleRain} visible simultaneously)`)}
  const one=await at(.45,'one-selected');if(one.selected<.25)fail(`${label}:one-selected`,'one selected coconut is not clearly visible');if(one.visibleRain>3)fail(`${label}:one-selected`,`${one.visibleRain} rain fruits still distract from selected coconut`);
  const cut=await at(.61,'knife-cut');if(cut.hero<.2)fail(`${label}:knife-cut`,'protected cut scene is not visible');if(cut.knife<.15)fail(`${label}:knife-cut`,'knife does not visibly cross the crown');if(cut.frameRect&&(cut.frameRect.width<viewport.width*.9||cut.frameRect.height<viewport.height*.9))fail(`${label}:knife-cut`,'cut image is floating as a small rectangle instead of filling the scene');
  const body=await at(.67,'body-cut');if(body.body<.2)fail(`${label}:body-cut`,'body-cut frame is not visible');
  const splash=await at(.76,'cap-splash');if(splash.cap<.15)fail(`${label}:cap-splash`,'cap/open frame is not visible');if(splash.splash<.2)fail(`${label}:cap-splash`,'water splash is not visible');
  const water=await at(.85,'water-finish');if(water.water<.25)fail(`${label}:water-finish`,'photographic water finish is not visible');
  await page.close();
 }
 await audit({width:1440,height:900},'desktop');await audit({width:1024,height:768},'laptop');
}finally{await browser.close()}
const report={generatedAt:new Date().toISOString(),failures,checks};fs.writeFileSync(path.join(OUT,'cinematic-qa-report.json'),JSON.stringify(report,null,2));const summary=['# Natural harvest cinematic QA','',`Failures: ${failures.length}`,'',...(failures.length?failures.map(x=>`- **${x.scope}** — ${x.msg}`):['- None']),'','Checks: 100 total fruits across staggered waves; no more than 32 on screen; one selected fruit; protected full-screen cut frames; local knife; cap/splash; photographic water finish; compact 235vh runway.'].join('\n');fs.writeFileSync(path.join(OUT,'cinematic-qa-summary.md'),summary);console.log(summary);if(failures.length)process.exit(1);
